# gitdocx/action.yml
name: GitDocx Enhanced Builder
description: Set up Docker Buildx with QEMU, caching, and bake support.

inputs:
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-password:
    description: Docker Hub password or token
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx (Enhanced)
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver: docker-container
        driver-opts: |
          network=host
          env.BUILDKIT_STEP_LOG_MAX_SIZE=10000000
          env.BUILDKIT_STEP_LOG_MAX_SPEED=10485760
        buildkitd-flags: --debug
        use: true

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
